version: "3"
name: mongo-sharding-repl

x-mongo-config: &mongo-config
  image: mongo:latest
  networks:
    - app-network
  restart: always

  healthcheck:
    test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    interval: 5s
    start_period: 10s

x-config-server: &config-server
  <<: *mongo-config
  command: [
    "--configsvr", # запуск в режиме конфигурации
    "--replSet",
    "config_server",
    "--bind_ip_all",
    "--port",
    "27017",
  ]
  
x-mongos-router: &mongos-router
  <<: *mongo-config
  command: mongos --configdb config_server/config-server-1:27017,config-server-2:27017,config-server-3:27017 --bind_ip_all --port 27017
  depends_on:
    - config-server-1
    - config-server-2
    - config-server-3
    - shard1-1
    - shard1-2
    - shard1-3
    - shard2-1
    - shard2-2
    - shard2-3
    - shard3-1
    - shard3-2
    - shard3-3


services:
  # config servers 
  config-server-1:
    <<: *config-server
    container_name: config-server-1
    volumes:
      - config-server-1-data:/data/db
  
  config-server-2:
    <<: *config-server
    container_name: config-server-2
    volumes:
      - config-server-2-data:/data/db

  config-server-3:
    <<: *config-server
    container_name: config-server-3
    volumes:
      - config-server-3-data:/data/db

  # routers 
  mongos-1:
    <<: *mongos-router
    container_name: mongos-1
    ports:
      - "27020:27017"

  mongos-2:
    <<: *mongos-router
    container_name: mongos-2
    ports:
      - "27018:27017"

  mongos-3:
    <<: *mongos-router
    container_name: mongos-3
    ports:
      - "27019:27017"

  # shards
  shard1-1:
    <<: *mongo-config
    container_name: shard1-1
    command: [
      "--shardsvr", 
      "--replSet",
      "shard1",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard1-1-data:/data/db

  shard1-2:
    <<: *mongo-config
    container_name: shard1-2
    command: [
      "--shardsvr", 
      "--replSet",
      "shard1",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard1-2-data:/data/db

  shard1-3:
    <<: *mongo-config
    container_name: shard1-3
    command: [
      "--shardsvr", 
      "--replSet",
      "shard1",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard1-3-data:/data/db

      # //2-й шард
  shard2-1:
    <<: *mongo-config
    container_name: shard2-1
    command: [
      "--shardsvr", 
      "--replSet",
      "shard2",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard2-1-data:/data/db

  shard2-2:
    <<: *mongo-config
    container_name: shard2-2
    command: [
      "--shardsvr", 
      "--replSet",
      "shard2",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard2-2-data:/data/db

  shard2-3:
    <<: *mongo-config
    container_name: shard2-3
    command: [
      "--shardsvr", 
      "--replSet",
      "shard2",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard2-3-data:/data/db

  shard3-1:
    <<: *mongo-config
    container_name: shard3-1
    command: [
      "--shardsvr", 
      "--replSet",
      "shard3",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard3-1-data:/data/db

  shard3-2:
    <<: *mongo-config
    container_name: shard3-2
    command: [
      "--shardsvr", 
      "--replSet",
      "shard3",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard3-2-data:/data/db

  shard3-3:
    <<: *mongo-config
    container_name: shard3-3
    command: [
      "--shardsvr", 
      "--replSet",
      "shard3",
      "--port", 
      "27017", 
      "--dbpath", 
      "/data/db",
      "--bind_ip_all"
    ]
    volumes:
      - shard3-3-data:/data/db

  pymongo_api:
    container_name: pymongo_api
    build:
      context: ../api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos-1
      - mongos-2
      - mongos-3
    ports:
      - 8080:8080
    networks:
    - app-network 
    environment:
      MONGODB_URL: "mongodb://mongos-1:27017,mongos-2:27017,mongos-3:27017"
      MONGODB_DATABASE_NAME: "somedb"

networks:
  app-network:
    driver: bridge

volumes:
  config-server-1-data:
  config-server-2-data: 
  config-server-3-data:
  shard1-1-data:
  shard1-2-data:
  shard1-3-data:
  shard2-1-data:
  shard2-2-data:
  shard2-3-data:
  shard3-1-data:
  shard3-2-data:
  shard3-3-data:
